elimu-ai/kukariri

app/build.gradle, app/src/main/java/ai/elimu/kukariri/assessment/WordAssessmentActivity.java, app/src/main/java/ai/elimu/kukariri/util/CursorToEmojiGsonConverter.java
- Append Emojis (if any) below the Word
=> #9 Add "show answer" button

app/build.gradle
=> Upgrade to model-2.0.66

app/build.gradle
Resolve issue: #31
Fix build error: `Could not find com.daasuu:EasingInterpolator:1.3.0`
=> Fix build error: Could not find com.daasuu:EasingInterpolator:1.3.0

app/src/main/res/values-th/strings.xml
=> chore: add i18n for thai

app/build.gradle, gradle/libs.versions.toml
=> Add Kotlin standard lib to fix a runtime crash: #52

app/build.gradle, app/src/main/java/ai/elimu/kukariri/BaseApplication.java, app/src/main/java/ai/elimu/kukariri/assessment/WordAssessmentActivity.kt, build.gradle, gradle/libs.versions.toml
=> Play audio when clicking on a word

build.gradle
Remove jcenter() as it's [sunsetting](https://jfrog.com/blog/jcenter-sunset/).
=> Remove jcenter() as it's sunsetting

.github/workflows/connected-check_api-29.yml, app/src/androidTest/java/ai/elimu/kukariri/ExampleInstrumentedTest.java
=> test: android emulator workflow

gradle/libs.versions.toml
=> chore(deps): content-provider-1.2.34

gradle/libs.versions.toml
=> chore(deps): common-utils 1.0.8

app/src/main/java/ai/elimu/kukariri/assessment/WordAssessmentActivity.kt
Increase gap between word and emoji
* Resolves #87
=> Increase gap between word and emoji

gradle/libs.versions.toml
https://github.com/elimu-ai/content-provider/releases/tag/1.2.38
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.2.38

README.md
=> document how to use mavenlocal with utils libraries

README.md, app/build.gradle
=> build(apk): publish on jitpack

gradle/libs.versions.toml
=> chore(deps): common-utils 1.0.10

gradle/libs.versions.toml
https://github.com/elimu-ai/content-provider/releases/tag/1.2.39
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.2.39

README.md, app/build.gradle, gradle/libs.versions.toml
https://github.com/elimu-ai/common-utils/releases/tag/1.0.11
* Resolves #
* 
* 
*
*
=> chore(deps): common-utils 1.0.11

gradle/libs.versions.toml
https://github.com/elimu-ai/analytics/releases/tag/3.1.31
* Resolves #
* 
* 
*
*
=> chore(deps): analytics 3.1.31

gradle/libs.versions.toml
https://github.com/elimu-ai/content-provider/releases/tag/1.2.40
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.2.40

.github/workflows/gradle-release.yml, app/build.gradle
=> chore: create git tag on push to `main`

app/build.gradle, gradle/libs.versions.toml
Remove dependencies that are already included in the Analytics library.
https://github.com/elimu-ai/analytics/releases/tag/3.2.0
* Resolves #
* 
* 
*
*
=> chore(deps): analytics 3.2.0

.github/workflows/gradle-release.yml, README.md, app/build.gradle, gradle/libs.versions.toml
Remove dependencies that are included in the new Content Provider library: https://github.com/elimu-ai/content-provider/releases/tag/1.3.0
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.3.0

gradle/libs.versions.toml
Update Content Provider to 1.3.5
=> Update Content Provider to 1.3.5

gradle/libs.versions.toml
https://github.com/elimu-ai/content-provider/releases/tag/1.4.27
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.4.27

gradle/libs.versions.toml
* Resolves #
Update Content Provider to 1.4.38
* 
*
*
=> Update Content Provider to 1.4.38

gradle/libs.versions.toml
https://github.com/elimu-ai/content-provider/releases/tag/1.4.41
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.4.41

.github/workflows/connected-check.yml, app/build.gradle, gradle/libs.versions.toml
https://github.com/elimu-ai/content-provider/releases/tag/1.4.64
* Resolves #
* 
* 
*
*
=> chore(deps): content-provider 1.4.64
